---
# tasks file for netzwirt.nexus-oss


- name: create group for nexus
  group: 
    name: "{{nexus_oss_group}}"
    state: present


- name: create system-user for nexus
  user: 
    name: "{{nexus_oss_user}}"
    group: "{{nexus_oss_group}}"
    system: yes
    state: present


- name: install wget
  apt:
    name: wget
    state: present


- name: download nexus oss
  get_url: 
    url: "http://download.sonatype.com/nexus/oss/nexus-{{nexus_oss_version}}-bundle.tar.gz"
    dest: "/tmp/{{nexus_oss_version}}"


- name: ensure installation directory exists
  file:
    path: "{{nexus_oss_installation_dir}}"
    state: directory
    owner: "{{nexus_oss_user}}"
    group: "{{nexus_oss_group}}"


- name: ensure working directory exists
  file:
    path: "{{nexus_oss_working_dir}}"
    state: directory
    owner: "{{nexus_oss_user}}"
    group: "{{nexus_oss_group}}"
    mode: 0755
    recurse: true


- name: unpack nexus
  unarchive:
    src: "/tmp/{{nexus_oss_version}}"
    dest: "{{nexus_oss_installation_dir}}"
    creates: "{{nexus_oss_installation_dir}}/nexus-{{nexus_oss_version}}"
    copy: no
    owner: "{{nexus_oss_user}}"
    group: "{{nexus_oss_group}}"
    mode: 0755


- name: ensure new installation os owned by nexus user
  file:
    path: "{{nexus_oss_installation_dir}}/nexus-{{nexus_oss_version}}"
    owner: "{{nexus_oss_user}}"
    group: "{{nexus_oss_group}}"
    recurse: true


- name: link current version
  file:
    state: link
    src: "{{nexus_oss_installation_dir}}/nexus-{{nexus_oss_version}}"
    name: "{{nexus_oss_installation_dir}}/current-nexus"


- name: configure port
  lineinfile:
    dest: "{{nexus_oss_installation_dir}}/current-nexus/conf/nexus.properties"
    line: "application-port={{nexus_oss_port}}"
    regexp: "application-port=.*"
    state: present
  notify:
    - restart nexus


- name: configure working directory
  lineinfile:
    dest: "{{nexus_oss_installation_dir}}/current-nexus/conf/nexus.properties"
    line: "nexus-work={{nexus_oss_working_dir}}"
    regexp: "nexus-work=.*"
    state: present
  notify:
    - restart nexus


- name: configure context path
  lineinfile:
    dest: "{{nexus_oss_installation_dir}}/current-nexus/conf/nexus.properties"
    line: "nexus-webapp-context-path={{nexus_oss_context_path}}"
    regexp: "nexus-webapp-context-path=.*"
    state: present
  notify:
    - restart nexus


- name: create pid directory
  file:
    path: /var/run/nexus
    owner: "{{nexus_oss_user}}"
    group: "{{nexus_oss_group}}"
    state: directory
       
       
- name: change homedir in init-script
  replace: 
    dest: "{{nexus_oss_installation_dir}}/current-nexus/bin/nexus"
    regexp: '^NEXUS_HOME=(.*)$' 
    replace: 'NEXUS_HOME={{nexus_oss_installation_dir}}/current-nexus'


- name: change user in init-script
  replace: 
    dest: "{{nexus_oss_installation_dir}}/current-nexus/bin/nexus"
    regexp: "^#RUN_AS_USER=(.*)$"
    replace: "RUN_AS_USER={{nexus_oss_user}}"


- name: change pid directory in init-script
  replace: 
    dest: "{{nexus_oss_installation_dir}}/current-nexus/bin/nexus"
    regexp: "^#PIDDIR=(.*)$"
    replace: "PIDDIR=/var/run/nexus"


- name: copy init-script to /etc/init.d
  command: cp "{{nexus_oss_installation_dir}}/current-nexus/bin/nexus" /etc/init.d/nexus 
    creates=/etc/init.d/nexus
  notify:
    - start nexus
